dist: xenial
language: python
addons:
  apt:
    packages:
      - ldap-utils
      - slapd
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
install:
  - pip install -r requirements/tests.txt
  - pip install -e .
script:
  - flake8 src
  - coverage run --source='src' -m django test --settings tests.settings
  - coverage report
